# Generated by Django 4.1 on 2022-09-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('acronym', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=2000)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.domain')),
            ],
        ),
    ]
