# Generated by Django 4.1 on 2022-09-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_domain_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='area',
            new_name='domain',
        ),
    ]
