# Generated by Django 4.1 on 2022-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_rename_area_entry_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
