# Generated by Django 4.1 on 2022-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_alter_domain_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
